{"ast":null,"code":"import Router from \"next/router\";\nimport { error_open } from \"../reducers/utilsinfo\";\nlet dispatch;\nlet getState;\nexport const setDispatch = dispatch => {\n  dispatch = dispatch;\n};\nexport const setStateFuc = getState => {\n  getState = getState;\n};\nexport const errorExcute = (code, params, cb) => {\n  switch (code) {\n    case 403:\n      alert(\"사용자의 다른 기기에서 로그인되었습니다. 로그아웃됩니다.\");\n      Router.push(\"/\");\n      if (cb) cb();\n      break;\n\n    case 500:\n      let errorObj = {\n        code: code,\n        ok: \"다시 시도\",\n        cancel: \"홈으로\",\n        msg: \"이런, 일시적으로 서비스에 장애가 발생한 것 같습니다. 다시 시도해보시고 이러한 증상이 계속되면 앱을 재실행해보시기 바랍니다.\"\n      };\n      return (dispatch, getState) => {\n        error_open(errorObj)(dispatch, getState);\n      };\n      break;\n\n    default:\n      break;\n  }\n};","map":{"version":3,"sources":["/Users/daehankim/Documents/GitHub/blogshot/logic/errorLogic.js"],"names":["Router","error_open","dispatch","getState","setDispatch","setStateFuc","errorExcute","code","params","cb","alert","push","errorObj","ok","cancel","msg"],"mappings":"AAAA,OAAOA,MAAP,MAAmB,aAAnB;AACA,SAASC,UAAT,QAA2B,uBAA3B;AAEA,IAAIC,QAAJ;AACA,IAAIC,QAAJ;AAEA,OAAO,MAAMC,WAAW,GAAGF,QAAQ,IAAI;AACnCA,EAAAA,QAAQ,GAAGA,QAAX;AACH,CAFM;AAGP,OAAO,MAAMG,WAAW,GAAGF,QAAQ,IAAI;AACnCA,EAAAA,QAAQ,GAAGA,QAAX;AACH,CAFM;AAIP,OAAO,MAAMG,WAAW,GAAG,CAACC,IAAD,EAAOC,MAAP,EAAeC,EAAf,KAAsB;AAC7C,UAAQF,IAAR;AACI,SAAK,GAAL;AACIG,MAAAA,KAAK,CAAC,iCAAD,CAAL;AACAV,MAAAA,MAAM,CAACW,IAAP,CAAY,GAAZ;AACA,UAAIF,EAAJ,EAAQA,EAAE;AACV;;AACJ,SAAK,GAAL;AACI,UAAIG,QAAQ,GAAG;AACXL,QAAAA,IAAI,EAAEA,IADK;AAEXM,QAAAA,EAAE,EAAE,OAFO;AAGXC,QAAAA,MAAM,EAAE,KAHG;AAIXC,QAAAA,GAAG,EACC;AALO,OAAf;AAOA,aAAO,CAACb,QAAD,EAAWC,QAAX,KAAwB;AAC3BF,QAAAA,UAAU,CAACW,QAAD,CAAV,CAAqBV,QAArB,EAA+BC,QAA/B;AACH,OAFD;AAGA;;AAEJ;AACI;AApBR;AAsBH,CAvBM","sourcesContent":["import Router from \"next/router\";\nimport { error_open } from \"../reducers/utilsinfo\";\n\nlet dispatch;\nlet getState;\n\nexport const setDispatch = dispatch => {\n    dispatch = dispatch;\n};\nexport const setStateFuc = getState => {\n    getState = getState;\n};\n\nexport const errorExcute = (code, params, cb) => {\n    switch (code) {\n        case 403:\n            alert(\"사용자의 다른 기기에서 로그인되었습니다. 로그아웃됩니다.\");\n            Router.push(\"/\");\n            if (cb) cb();\n            break;\n        case 500:\n            let errorObj = {\n                code: code,\n                ok: \"다시 시도\",\n                cancel: \"홈으로\",\n                msg:\n                    \"이런, 일시적으로 서비스에 장애가 발생한 것 같습니다. 다시 시도해보시고 이러한 증상이 계속되면 앱을 재실행해보시기 바랍니다.\"\n            };\n            return (dispatch, getState) => {\n                error_open(errorObj)(dispatch, getState);\n            };\n            break;\n\n        default:\n            break;\n    }\n};\n"]},"metadata":{},"sourceType":"module"}